### ISSUE TITLE
Some tests are failing when twig get's updated to 1.38.1.

### ISSUE THREAD

**Issue by Jaesin** [deviantintegral/drupal_tests#51]
Drupal core 8.6.11 was just released which fixes an issue with twig by requiring version 1.38.2. Updating this image to 8.6.11 would solve the `"Attribute "name" does not exist for Node "Twig\Node\CheckToStringNode"."` issue.

**Comment by Jaesin** [comment]
Uh, make that 8.6.12. See: https://www.drupal.org/project/drupal/releases/8.6.12

**Comment by deviantintegral** [comment]
This has taken longer because Docker Hub totally broke their build UI. I had to delete all of the configuration and start over. It turns out the new "build caching" feature doesn't detect upstream changes of tags like `8.6-apache`, so what I triggered yesterday was only 8.6.11. There _should_ be a 8.6.12 build in 20 minutes or so.

I need to get a rebuild of our `0.3.4` tag which is Drupal 8.5 as well, but something in coder has broken there too.

An 8.7.0 alpha was just released this week, so I'll be starting to get images up for that. As a part of that, I'm going to see if anything can replace Docker Hub so we can have reliable autobuilds. I may end up having to wire up a weekly Circle CI job to force rebuilds.

**Comment by deviantintegral** [comment]
Gah - it turns out the official Drupal image still doesn't have an `8.6.12` build. I'm blocked updating until that's done.

```
docker pull drupal:8.6-apache  && docker run --rm drupal:8.6-apache cat /var/www/html/core/modules/system/system.info.yml
8.6-apache: Pulling from library/drupal
Digest: sha256:167dfa39c920c3820f3d1ef4de8f09593d687b4d319db8ad9f20eac2f0c920c3
Status: Image is up to date for drupal:8.6-apache
name: System
type: module
description: 'Handles general site configuration for administrators.'
package: Core
# version: VERSION
# core: 8.x
required: true
configure: system.admin_config_system

# Information added by Drupal.org packaging script on 2019-03-13
version: '8.6.11'
core: '8.x'
project: 'drupal'
datestamp: 155251163

$ docker pull drupal:8.6.12-apache
Error response from daemon: manifest for drupal:8.6.12-apache not found
```

**Comment by deviantintegral** [comment]
I've pushed a `0.3.5` tag for `8.5.x` and have got that reconciled against master at #54. Still waiting on an upstream 8.6.12 release.

**Comment by deviantintegral** [comment]
Images are updated with 8.6.13 and 8.5.14. Feel free to re-open if you have any trouble.
